/* KENVEN HUB - runtime feature patch */
'use strict';
(function(){
  const isMain=!!document.getElementById('app-container');
  const isAdmin=!!document.getElementById('admin-dashboard');
  if(!isMain&&!isAdmin)return;
  window.KenvenHub=window.KenvenHub||{};
  const KH=window.KenvenHub;
  KH.safe=v=>{if(typeof Utils!=='undefined'&&Utils.escapeHtml)return Utils.escapeHtml(String(v??''));const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
  KH.rank=(total,manual)=>{if(typeof CONFIG!=='undefined'&&Array.isArray(CONFIG.ranks)){if(manual&&manual!=='auto')return CONFIG.ranks.find(r=>r.id===manual)||CONFIG.ranks[0];const n=Number(total)||0;let r=CONFIG.ranks[0];for(const x of CONFIG.ranks)if(n>=x.minCoins)r=x;return r}const n=Number(total)||0;if(manual&&manual!=='auto')return{id:manual,name:{en:manual,ar:manual},dailyGift:10};if(n>=1500)return{id:'vip',name:{en:'VIP',ar:'VIP'},dailyGift:10};if(n>=800)return{id:'diamond',name:{en:'Diamond',ar:'ألماسي'},dailyGift:7};if(n>=400)return{id:'platinum',name:{en:'Platinum',ar:'بلاتيني'},dailyGift:5};if(n>=150)return{id:'gold',name:{en:'Gold',ar:'ذهبي'},dailyGift:3};if(n>=50)return{id:'silver',name:{en:'Silver',ar:'فضي'},dailyGift:2};return{id:'bronze',name:{en:'Bronze',ar:'برونز'},dailyGift:1};};
  function loadRankConfig(){if(!isMain||typeof Data==='undefined'||!Array.isArray(Data.settings?.rankConfig)||!Array.isArray(CONFIG.ranks))return;const merged=Data.settings.rankConfig.map((x,i)=>({...CONFIG.ranks[i],...x}));if(merged.length===CONFIG.ranks.length)CONFIG.ranks=merged}
  async function loadUser(){if(!isMain||typeof FB==='undefined'||!FB.ok||!FB.user)return null;try{const s=await FB.db.collection('users').doc(FB.user.uid).get();const u=s.exists?s.data():{};if(typeof Coins!=='undefined')Coins.userRecord=u;return u}catch(_){return null}}
  function installStyles(){if(document.getElementById('kh-runtime-style'))return;const s=document.createElement('style');s.id='kh-runtime-style';s.textContent='.profile-enhanced{padding:4px}.profile-hero{display:flex;gap:16px;align-items:center;margin-bottom:18px}.profile-avatar-fallback{display:grid;place-items:center;background:var(--card);font-size:1.8rem;font-weight:800}.profile-email{color:var(--text-muted);font-size:.8rem;margin-top:5px}.profile-preferences{display:grid;gap:10px;margin-top:18px}.profile-preferences label{display:grid;gap:5px;color:var(--text-secondary);font-size:.85rem}.card-box{background:var(--card);border:1px solid var(--glass-border);border-radius:14px;padding:16px;margin:14px 0}.rank-badge{display:inline-flex;align-items:center;gap:4px}.rewards-link-inline{margin-top:6px}.kh-admin-ranks{display:grid;gap:8px}.kh-rank-row{display:grid;grid-template-columns:1.1fr 1fr 1fr;gap:8px;align-items:center}.kh-admin-note{font-size:.8rem;color:var(--text-muted)}@media(max-width:600px){.kh-rank-row{grid-template-columns:1fr}}';document.head.appendChild(s)}

  if(isMain){
    installStyles();loadRankConfig();
    if(typeof Coins!=='undefined'){
      const oldInit=Coins.init?.bind(Coins),oldAuth=Coins.onAuthChange?.bind(Coins);Coins.userRecord=null;
      Coins.getRank=function(){return KH.rank(this.wallet?.totalEarned||this.userRecord?.totalEarned||0,this.userRecord?.manualRank||this.wallet?.manualRank)};
      Coins.getDailyGiftAmount=function(){return Number(this.getRank().dailyGift??Data.settings.dailyGiftAmount??1)};
      Coins.init=async function(){const r=oldInit?await oldInit():undefined;await loadUser();return r};
      if(oldAuth)Coins.onAuthChange=async function(u){const r=await oldAuth(u);await loadUser();return r};
      Coins.transferCoins=async function(toCode,amount){const targetCode=String(toCode||'').trim(),n=Math.floor(Number(amount)||0);if(!this.wallet||n<=0)return false;if((this.wallet.balance||0)<n){UI.showToast(I18n.t('coins.notEnough'),'warning');return false}if(!targetCode||targetCode===this.wallet.id){UI.showToast(I18n.t('coins.sameWallet'),'warning');return false}if(!FB.ok){UI.showToast(I18n.t('coins.offline'),'warning');return false}try{const sRef=FB.db.collection('wallets').doc(this.wallet.id),tRef=FB.db.collection('wallets').doc(targetCode),log=FB.db.collection('coin_transfers').doc(Utils.genId());await FB.db.runTransaction(async tx=>{const s=await tx.get(sRef),t=await tx.get(tRef);if(!s.exists||!t.exists)throw Error('NOT_FOUND');const a=s.data()||{},b=t.data()||{};if(a.transferred||b.transferred||(a.balance||0)<n)throw Error('INVALID');tx.update(sRef,{balance:(a.balance||0)-n,updatedAt:Date.now()});tx.update(tRef,{balance:firebase.firestore.FieldValue.increment(n),updatedAt:Date.now()});tx.set(log,{id:log.id,fromWallet:this.wallet.id,toWallet:targetCode,amount:n,fromUid:a.ownerUid||null,toUid:b.ownerUid||null,at:Date.now()})});this.wallet.balance=(this.wallet.balance||0)-n;await Mirror.writeWallet(this.wallet);this.updateUI();UI.showToast(I18n.t('transfer.success'),'success');return true}catch(e){UI.showToast(I18n.t('coins.invalidCode'),'error');return false}};
    }
    if(typeof Chat!=='undefined){
      Chat.send=async function(){const input=document.getElementById('chat-input'),content=(input?.value||'').trim();if(!content||content.length>100)return;if(!FB.ok){UI.showToast(I18n.t('coins.offline'),'warning');return}const u=FB.user,r=Coins.getRank();try{await FB.db.collection('chat').add({content,authorName:u?(u.displayName||u.email.split('@')[0]):'Guest',userUid:u?.uid||null,userRank:r.id,manualRank:Coins.userRecord?.manualRank||null,totalEarned:Coins.wallet?.totalEarned||0,createdAt:Date.now()});input.value='';const c=document.getElementById('chat-char-count');if(c)c.textContent='0/100'}catch(_){UI.showToast(I18n.t('toast.error'),'error')}};
      Chat.render=function(){const c=document.getElementById('chat-messages');if(!c)return;if(!this.messages.length){c.innerHTML='<div class="chat-empty">'+I18n.t('chat.empty')+'</div>';return}c.innerHTML=this.messages.map(m=>{const r=KH.rank(m.totalEarned||0,m.manualRank||m.userRank);return '<div class="chat-message"><div class="chat-msg-avatar">'+KH.safe((m.authorName||'?').charAt(0).toUpperCase())+'</div><div class="chat-msg-content"><div class="chat-msg-header"><span class="chat-msg-author">'+KH.safe(m.authorName||'Anonymous')+'</span><span class="rank-badge '+r.id+' chat-msg-rank">'+KH.safe(r.name?.[I18n.lang]||r.name||r.id)+'</span><span class="chat-msg-time">'+Utils.timeAgo(m.createdAt)+'</span></div><div class="chat-msg-text">'+KH.safe(m.content||'')+'</div></div></div>'}).join('');c.scrollTop=c.scrollHeight};
    }
    if(typeof Comments!=='undefined'){const old=Comments.submit.bind(Comments);Comments.submit=async function(pid,parentId=null){if(!FB.user)return old(pid,parentId);const root=parentId?document.getElementById('rf-'+parentId):document.getElementById('comment-form'),content=(root?.querySelector('.rf-content')?.value||document.getElementById('comment-content')?.value||'').trim();if(!content)return;const cm={id:Utils.genId(),postId:pid,parentId,authorName:FB.user.displayName||FB.user.email.split('@')[0],authorEmail:FB.user.email,content,isAdmin:false,approved:true,likes:0,createdAt:Date.now(),userRank:Coins.getRank().id,userUid:FB.user.uid,userAvatar:FB.user.photoURL||null,totalEarned:Coins.wallet?.totalEarned||0,manualRank:Coins.userRecord?.manualRank||null};try{await FB.db.collection('comments').doc(cm.id).set(cm);UI.showToast(I18n.t('comments.success'),'success');this.render(pid,await this.load(pid));if(!parentId)document.getElementById('comment-form')?.reset()}catch(_){UI.showToast(I18n.t('toast.error'),'error')}}}
    if(typeof Profile!=='undefined')Profile.render=async function(){const c=document.getElementById('profile-content');if(!c)return;if(!FB.user){c.innerHTML='<div class="empty">'+I18n.t('profile.login')+'</div>';return}const u=await loadUser()||{},name=u.name||FB.user.displayName||FB.user.email.split('@')[0],avatar=u.avatarUrl||FB.user.photoURL||'',prefs=u.preferences||{},r=Coins.getRank(),read=Object.keys(LS.get(CONFIG.keys.readProgress,{})||{}).length,bm=(LS.get(CONFIG.keys.bookmarks,[])||[]).length;c.innerHTML='<div class="profile-enhanced"><div class="profile-hero"><div class="profile-avatar-large profile-avatar-fallback">'+KH.safe(name.charAt(0).toUpperCase())+'</div><div><h3>'+KH.safe(name)+'</h3><span class="rank-badge '+r.id+'">'+KH.safe(r.name?.[I18n.lang]||r.name||r.id)+'</span><div class="profile-email">'+KH.safe(FB.user.email)+'</div></div></div><div class="profile-stats-grid"><div class="profile-stat"><div class="profile-stat-value">'+(Coins.wallet?.totalEarned||0)+'</div><div class="profile-stat-label">'+I18n.t('profile.coinsEarned')+'</div></div><div class="profile-stat"><div class="profile-stat-value">'+read+'</div><div class="profile-stat-label">'+I18n.t('profile.postsRead')+'</div></div><div class="profile-stat"><div class="profile-stat-value">'+bm+'</div><div class="profile-stat-label">'+I18n.t('reading.saved')+'</div></div></div><div class="profile-preferences"><label>Avatar URL<input id="profile-avatar-url" class="form-input" value="'+KH.safe(avatar)+'"></label><label>Language<select id="profile-language" class="form-select"><option value="en" '+(prefs.language==='en'?'selected':'')+'>English</option><option value="ar" '+(prefs.language==='ar'?'selected':'')+'>العربية</option></select></label><label>Theme<select id="profile-theme" class="form-select"><option value="dark" '+(prefs.theme==='dark'?'selected':'')+'>Dark</option><option value="light" '+(prefs.theme==='light'?'selected':'')+'>Light</option></select></label><button id="profile-save-btn" class="btn btn-primary">Save Profile</button></div></div>';document.getElementById('profile-save-btn')?.addEventListener('click',async()=>{const avatarUrl=document.getElementById('profile-avatar-url').value.trim(),language=document.getElementById('profile-language').value,theme=document.getElementById('profile-theme').value;await FB.db.collection('users').doc(FB.user.uid).set({name,avatarUrl,preferences:{language,theme},updatedAt:Date.now()},{merge:true});try{await FB.user.updateProfile({photoURL:avatarUrl||null})}catch(_){ }I18n.lang=language;LS.set(CONFIG.keys.lang,language);I18n.apply();Theme.current=theme;Theme.apply();await Profile.render();UI.showToast('Profile updated!','success')})};
    if(typeof Router!=='undefined'&&typeof Pages!=='undefined'){const old=Router.renderCurrent.bind(Router);Router.renderCurrent=function(){const r=old();setTimeout(()=>{try{if(!location.hash.startsWith('#post/'))return;const p=Data.bySlug(location.hash.split('/')[1]);if(!p?.isAffiliate)return;const page=document.querySelector('.post-page');if(!page||page.querySelector('.inline-affiliate'))return;const a=(p.affiliateIds||[]).map(id=>Data.affiliate.find(x=>x.id===id)).find(Boolean)||Data.affiliate[0];if(!a)return;const box=document.createElement('div');box.className='inline-affiliate';box.innerHTML='<div class="inline-affiliate-icon"><i class="fas '+KH.safe(a.icon||'fa-tag')+'"></i></div><div class="inline-affiliate-info"><div class="inline-affiliate-name">'+KH.safe(a.name||'Offer')+'</div><div class="inline-affiliate-stars">★ '+Number(a.rating||5)+'</div><div class="inline-affiliate-desc">'+KH.safe(a.description||'')+'</div></div><a href="'+KH.safe(a.url||'#')+'" target="_blank" rel="noopener noreferrer nofollow" class="btn btn-gold btn-sm">'+I18n.t('affiliate.visit')+'</a>';const content=page.querySelector('.post-content');(content||page).appendChild(box)}catch(_){ }},300);return r};}
    if(typeof Coins!=='undefined')Coins.adEarn=function(){if(!Data.settings.enableAd||this.adTimer||!this.wallet)return;const wait=Math.max(5,Number(Data.settings.adWaitSeconds||30)),adUrl=Data.settings.adUrl||'#';open(adUrl,'_blank','noopener');let left=wait;const b=document.getElementById('ad-earn-btn'),t=document.getElementById('ad-timer-text');if(b)b.disabled=true;if(t)t.textContent='Wait '+left+'s';this.adTimer=setInterval(async()=>{left--;if(t)t.textContent='Wait '+left+'s';if(left<=0){clearInterval(this.adTimer);this.adTimer=null;if(b)b.disabled=false;await this.addCoins(Number(Data.settings.adRewardAmount||5));location.href='rewards.html'}},1000)};
    const addVideoUI=()=>{const body=document.querySelector('#coins-modal .coins-body');if(!body||document.getElementById('video-reward-box'))return;const box=document.createElement('div');box.id='video-reward-box';box.className='card-box';box.innerHTML='<h3><i class="fas fa-video"></i> Publish & Earn</h3><p>1000 views + 20 likes → 100 Coins + VIP after admin review.</p><input id="video-reward-url" class="form-input" placeholder="Video URL"><input id="video-reward-proof" class="form-input" placeholder="Screenshot proof URL"><div class="form-grid"><input id="video-reward-views" type="number" min="1000" class="form-input" placeholder="Views"><input id="video-reward-likes" type="number" min="20" class="form-input" placeholder="Likes"></div><button id="video-reward-submit" class="btn btn-primary">Submit for Review</button><a class="btn btn-secondary rewards-link-inline" href="rewards.html">View Coupons & Rewards</a>';body.appendChild(box);document.getElementById('video-reward-submit').onclick=async()=>{try{const id=await KH.submitVideoReward(document.getElementById('video-reward-url').value,document.getElementById('video-reward-proof').value,document.getElementById('video-reward-views').value,document.getElementById('video-reward-likes').value);UI.showToast('Submitted: '+id,'success')}catch(e){UI.showToast(e.message==='LOGIN_REQUIRED'?'Login required':e.message==='REQUIREMENTS_NOT_MET'?'Requirements not met':'Submission failed','warning')}}};
    if(typeof UI!=='undefined'){const old=UI.openModal.bind(UI);UI.openModal=function(id){const r=old(id);if(id==='coins-modal')setTimeout(addVideoUI,0);return r};setTimeout(addVideoUI,1000)}
    setTimeout(()=>{const nav=document.querySelector('.navbar-links');if(nav&&!document.getElementById('rewards-nav-link')){const a=document.createElement('a');a.id='rewards-nav-link';a.className='nav-link';a.href='rewards.html';a.innerHTML='<i class="fas fa-gift"></i> Rewards';nav.appendChild(a)}},800);
    try{if(matchMedia('(prefers-reduced-motion: reduce)').matches||innerWidth<=768){document.body.classList.add('effects-disabled');if(typeof Effects!=='undefined'){Effects.enabled=false;Effects.stopParticles?.()}}}catch(_){ }
  }
  if(isAdmin){
    setTimeout(()=>{try{if(typeof auth==='undefined'||typeof db==='undefined'||!auth.currentUser)return;db.collection('users').doc(auth.currentUser.uid).get().then(s=>{if(!s.exists||s.data()?.role!=='admin'){document.getElementById('admin-dashboard').style.display='none';document.getElementById('login-screen').style.display='grid';document.getElementById('login-error').textContent='Not authorized as admin.';document.getElementById('login-error').style.display='block';auth.signOut().catch(()=>{})}})}catch(_){ }},700);
    // Admin-only rank configuration without code changes.
    const installAdminControls=()=>{const settings=document.getElementById('tab-settings');if(!settings||document.getElementById('kh-rank-settings'))return;const box=document.createElement('div');box.id='kh-rank-settings';box.className='card-box';box.innerHTML='<h3>Ranks</h3><p class="kh-admin-note">Rank is based on total personally earned coins. Manual rank overrides are managed from Users.</p><div class="kh-admin-ranks">'+[['bronze','Bronze',0,1],['silver','Silver',50,2],['gold','Gold',150,3],['platinum','Platinum',400,5],['diamond','Diamond',800,7],['vip','VIP',1500,10]].map(x=>'<div class="kh-rank-row"><strong>'+x[1]+'</strong><input id="kh-rank-'+x[0]+'-min" type="number" min="0" class="form-input" value="'+x[2]+'"><input id="kh-rank-'+x[0]+'-gift" type="number" min="0" class="form-input" value="'+x[3]+'"></div>').join('')+'</div><button id="kh-save-ranks" class="btn btn-primary">Save Rank Rules</button>';settings.appendChild(box);db.collection('settings').doc('site').get().then(s=>{const cfg=s.data()?.rankConfig;if(Array.isArray(cfg))cfg.forEach(r=>{document.getElementById('kh-rank-'+r.id+'-min')?.setAttribute('value',r.minCoins??0);document.getElementById('kh-rank-'+r.id+'-gift')?.setAttribute('value',r.dailyGift??0)})});document.getElementById('kh-save-ranks').onclick=async()=>{const ids=['bronze','silver','gold','platinum','diamond','vip'];const rankConfig=ids.map(id=>({id,minCoins:Number(document.getElementById('kh-rank-'+id+'-min').value)||0,dailyGift:Number(document.getElementById('kh-rank-'+id+'-gift').value)||0}));await db.collection('settings').doc('site').set({rankConfig},{merge:true});alert('Rank rules saved')};};
    setTimeout(installAdminControls,900);
    // Keep public-setting names compatible with the main app.
    setTimeout(()=>{const b=document.getElementById('save-coin-settings-btn');if(!b)return;b.replaceWith(b.cloneNode(true));document.getElementById('save-coin-settings-btn').onclick=async()=>{const payload={dailyGiftAmount:Number(document.getElementById('coin-setting-daily').value)||0,adRewardAmount:Number(document.getElementById('coin-setting-ad-reward').value)||0,adWaitSeconds:Number(document.getElementById('coin-setting-ad-wait').value)||30,adUrl:document.getElementById('coin-setting-ad-url').value.trim(),whatsappNumber:document.getElementById('coin-setting-whatsapp').value.trim(),chatDeleteDays:Number(document.getElementById('coin-setting-chat-days').value)||3,onlineBoost:Number(document.getElementById('coin-setting-online-boost').value)||0,enableDailyGift:document.getElementById('coin-enable-daily').checked,enableAd:document.getElementById('coin-enable-ad').checked,enableWhatsapp:document.getElementById('coin-enable-whatsapp').checked,enableCodes:document.getElementById('coin-enable-codes').checked};await db.collection('settings').doc('site').set(payload,{merge:true});AUtils.toast('Coin settings saved','success')}} ,1100);
    // Description template helper.
    setTimeout(()=>{document.getElementById('apply-description-template')?.addEventListener('click',()=>{const q=Posts.quill;if(!q)return;const t=document.getElementById('description-template').value;const m={basic:'<h2>Overview</h2><p>What this resource is and why it is useful.</p><h2>Features</h2><ul><li>Feature 1</li><li>Feature 2</li></ul>',download:'<h2>About</h2><p>Short description.</p><h2>Download</h2><p>Installation and usage steps.</p>',tutorial:'<h2>Problem</h2><p>Describe the issue.</p><h2>Solution</h2><ol><li>Step one</li><li>Step two</li><li>Step three</li></ol>',affiliate:'<h2>Overview</h2><p>Describe the service.</p><h2>Offer</h2><p>Show the affiliate offer and the benefit.</p>'};if(m[t]){q.setContents([]);q.clipboard.dangerouslyPasteHTML(0,m[t])}})},1200);
  }
  KH.submitVideoReward=async(videoUrl,screenshotUrl,views,likes)=>{if(typeof FB==='undefined'||!FB.ok||!FB.user)throw Error('LOGIN_REQUIRED');const v=Number(views)||0,l=Number(likes)||0;if(!videoUrl||!screenshotUrl||v<1000||l<20)throw Error('REQUIREMENTS_NOT_MET');const id=typeof Utils!=='undefined'?Utils.genId():Date.now().toString(36);await FB.db.collection('video_reward_submissions').doc(id).set({id,uid:FB.user.uid,email:FB.user.email||'',videoUrl:String(videoUrl).trim(),screenshotUrl:String(screenshotUrl).trim(),claimedViews:v,claimedLikes:l,status:'pending',createdAt:Date.now()});return id};
})();
