/* KENVEN HUB - SERVICE WORKER v3 */
const CACHE_VERSION='kenven-hub-v3';
const CACHE_NAME='kenven-hub-'+CACHE_VERSION;
const CORE_ASSETS=['./','./index.html','./admin.html','./rewards.html','./style.css','./app.js','./admin.js','./feature-patch.js','./manifest.json'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(CORE_ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(names=>Promise.all(names.filter(n=>n!==CACHE_NAME).map(n=>caches.delete(n)))).then(()=>self.clients.claim())));
async function patchedHtml(response){try{const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let text=await response.text();if(!text.includes('feature-patch.js'))text=text.replace(/<\/body>/i,'<script src="feature-patch.js" defer></script></body>');return new Response(text,{status:response.status,statusText:response.statusText,headers:response.headers})}catch(_){return response}}
self.addEventListener('fetch',e=>{const req=e.request,url=new URL(req.url);if(req.method!=='GET')return;if(url.hostname.includes('firebase')||url.hostname.includes('googleapis')||url.hostname.includes('gstatic'))return;if(url.origin===self.location.origin){e.respondWith(fetch(req).then(async r=>{if(req.mode==='navigate'&&url.pathname.endsWith('/index.html')||req.mode==='navigate'&&url.pathname==='/'){r=await patchedHtml(r)}const cache=await caches.open(CACHE_NAME);cache.put(req,r.clone());return r}).catch(()=>caches.match(req).then(x=>x||caches.match('./index.html'))));return}e.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(r=>{if(r&&r.status===200)caches.open(CACHE_NAME).then(c=>c.put(req,r.clone()));return r}).catch(()=>cached)))});
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
